# Generated by Django 5.2.11 on 2026-03-12 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_token_hash', models.CharField(db_index=True, help_text='Refresh token hash', max_length=64, unique=True)),
                ('revoked', models.BooleanField(db_index=True, default=False, help_text='Статус отзыва токена')),
                ('expires_at', models.DateTimeField(db_index=True, help_text='Время истечения токена')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Время создания токена')),
                ('revoked_at', models.DateTimeField(blank=True, help_text='Время отзыва токена', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
