# Generated by Django 4.2.4 on 2026-06-21 12:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=40, validators=[django.core.validators.RegexValidator(message='Введены недопустимые символы. Только кириллица, пробел, тире, дефис, от 2 до 40 символов.', regex='^[А-Яа-яЁё \\-—]{2,40}$')], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=40, null=True, validators=[django.core.validators.RegexValidator(message='Введены недопустимые символы. Только кириллица, пробел, тире, дефис, от 2 до 40 символов.', regex='^[А-Яа-яЁё \\-—]{2,40}$')], verbose_name='Фамилия'),
        ),
    ]
