# Generated by Django 4.2.4 on 2026-08-21 12:38

import django.core.validators
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users/avatars', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'png')), users.models.validate_avatar_size, users.models.validate_avatar_min_resolution], verbose_name='Аватарка'),
        ),
    ]
