# Generated by Django 4.2.4 on 2026-09-22 11:53

from django.db import migrations, models
from django.db.models import Q
from django.db.models.functions import Length

import users.validators

# Хардкод, а не константа из config: миграция должна остаться
# воспроизводимой, даже если NAME_LENGTH потом поменяют
NAME_LENGTH = 40

# Пробелы и дефисы/тире, которые не должны оставаться по краям после обрезки
EDGE_CHARACTERS = ' -—'


def truncate_long_names(apps, schema_editor):
    """Укорачивает имена и фамилии, которые не влезают в новую длину.

    Без этого AlterField падает на боевой базе:
    DataError: value too long for type character varying(40).
    """
    User = apps.get_model('users', 'User')

    too_long = (
        User.objects.annotate(
            first_name_length=Length('first_name'),
            last_name_length=Length('last_name'),
        )
        .filter(
            Q(first_name_length__gt=NAME_LENGTH) | Q(last_name_length__gt=NAME_LENGTH)
        )
        .only('id', 'first_name', 'last_name')
    )

    to_update = []
    for user in too_long.iterator():
        changed = False

        for field in ('first_name', 'last_name'):
            value = getattr(user, field) or ''
            if len(value) > NAME_LENGTH:
                setattr(user, field, value[:NAME_LENGTH].rstrip(EDGE_CHARACTERS))
                changed = True

        if changed:
            to_update.append(user)

    if to_update:
        User.objects.bulk_update(to_update, ['first_name', 'last_name'])


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0007_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.RunPython(truncate_long_names, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(
                max_length=40,
                validators=[users.validators.validate_person_name],
                verbose_name='Имя',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(
                blank=True,
                max_length=40,
                null=True,
                validators=[users.validators.validate_person_name],
                verbose_name='Фамилия',
            ),
        ),
    ]
