# Generated by Django 4.2.4 on 2026-09-22 12:34

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[users.validators.validate_email_length, users.validators.validate_email_domain_ascii], verbose_name='email'),
        ),
    ]
