# Generated by Django 4.2.4 on 2025-11-13 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Тип вопроса')),
            ],
            options={
                'verbose_name': 'Тип вопроса',
                'verbose_name_plural': 'Типы вопросов',
            },
        ),
        migrations.CreateModel(
            name='QuestionSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=50, verbose_name='Раздел')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='questions.questiontype', verbose_name='Тип вопроса')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='questions.questionsection', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('document', models.FileField(upload_to='questions/documents', verbose_name='Документ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_templates', to='questions.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Шаблон документа',
                'verbose_name_plural': 'Шаблоны документов',
            },
        ),
    ]
