services:

  postgres_prod:
    image: postgres:17
    env_file: ../.env.prod
    container_name: realty_postgres_prod
    environment:
      POSTGRES_DB: realty_db          # название базы
      POSTGRES_USER: realty_user      # имя пользователя
      POSTGRES_PASSWORD: strong_pass  # пароль
      POSTGRES_INITDB_ARGS: "--locale-provider=icu --icu-locale=ru-RU"
    volumes:
      - ../pgdata_prod:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB'" ]  # Проверка готовности PostgreSQL к работе.
      interval: 5s  # Интервал между проверками (5 секунд).
      timeout: 5s  # Время ожидания ответа от команды проверки.
      retries: 5  # Количество попыток перед переключением статуса на "неисправен".