services:

  postgres_prod:
    image: postgres:17
    env_file: ../.env.prod
    container_name: realty_postgres_prod
    environment:
      POSTGRES_DB: realty_db          # название базы
      POSTGRES_USER: realty_user      # имя пользователя
      POSTGRES_PASSWORD: strong_pass  # пароль
      POSTGRES_INITDB_ARGS: "--locale-provider=icu --icu-locale=ru-RU"
    volumes:
      - ../pgdata_prod:/var/lib/postgresql/data

    networks:
      - real_network

  backend_prod:
    build: .
    container_name: realty_django_prod
    env_file: ../.env.prod
    volumes:
      - .:/app
#      - static_data:/app/static/
      - ../media_prod:/app/media/
    ports:
      - 8080:8080  # Левое число — порт на хосте, Правое число — порт внутри контейнера
    restart: always  # Автоматический перезапуск контейнера при сбоях.
    depends_on:
      postgres_prod:
        condition: service_healthy
    networks:
      - real_network

  backend_test:
    build: .
    container_name: realty_django_test
    env_file: ../.env.test
    volumes:
      - .:/app
#      - static_data:/app/static/
      - ../media_test:/app/media/
    ports:
      - 8081:8080  # Левое число — порт на хосте, Правое число — порт внутри контейнера

    restart: always  # Автоматический перезапуск контейнера при сбоях.
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/"] # Assuming a health check endpoint exists
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - real_network

  nginx:
    image: nginx:latest
    ports:
      - 80:80   # HTTP
      - 443:443 # HTTPS
    volumes:
      - static_data:/app/static/  # Том для статики
      - ../media_prod:/var/www/media/prod/ # Путь для продакшен медиа внутри Nginx
      - ../media_test:/var/www/media/test/ # Путь для тестовых медиа внутри Nginx

      - ./nginx.conf:/etc/nginx/nginx.conf
#      - /var/kassa:/var/kassa
      - /etc/letsencrypt:/etc/letsencrypt  # Сертификаты
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    depends_on:
      - backend_prod
      - backend_test
    restart: always  # Перезапуск при сбоях
    networks:
      - real_network

networks:
  real_network:
    driver: bridge

volumes:
  static_data:  # кажется, использую внутреннюю папку static из джанго!
