# Generated by Django 4.2.4 on 2025-11-13 16:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realty_specificities', '0001_initial'),
        ('realty_addresses', '0001_initial'),
        ('realty_values', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Realty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=2000, verbose_name='Описание')),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Цена должна быть больше 0!')], verbose_name='Цена')),
                ('commission', models.PositiveIntegerField(blank=True, null=True, verbose_name='Комиссия')),
                ('published_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата и время публикации')),
                ('changed_at', models.DateTimeField(auto_now=True, verbose_name='Последнее изменение')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('about_apartment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='realty', to='realty_specificities.aboutapartment', verbose_name='О квартире')),
                ('about_building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='realty', to='realty_specificities.aboutbuilding', verbose_name='О доме')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='realty', to='realty_addresses.address', verbose_name='Адрес')),
                ('common_characteristics', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='realty', to='realty_specificities.commoncharacteristics', verbose_name='Общие характеристики')),
                ('communication_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='realty', to='realty_values.communicationmethod', verbose_name='Способ связи')),
            ],
            options={
                'verbose_name': 'Недвижимость',
                'verbose_name_plural': 'Недвижимость',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sale_profile', to='realty.realty')),
                ('sales_parameters', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='realty_specificities.salesparameters', verbose_name='Параметры продажи')),
            ],
            options={
                'verbose_name': 'Продажа',
                'verbose_name_plural': 'Продажи',
            },
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lease_payments', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rents', to='realty_specificities.leasepayments', verbose_name='Платежи аренды')),
                ('realty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rent_profile', to='realty.realty')),
                ('rental_features', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rents', to='realty_specificities.rentalfeatures', verbose_name='Особенности аренды')),
            ],
            options={
                'verbose_name': 'Аренда',
                'verbose_name_plural': 'Аренда',
            },
        ),
    ]
