# Generated by Django 4.2.4 on 2025-11-13 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('realty_values', '0001_initial'),
        ('realty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realty',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='realty', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='realty',
            name='owner_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='realty', to='realty_values.tradeparticipant', verbose_name='Тип владельца'),
        ),
        migrations.AddField(
            model_name='realty',
            name='realty_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='realty', to='realty_values.realtyadvstatus', verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='realty',
            name='realty_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='realty', to='realty_values.realtytype', verbose_name='Тип недвижимости'),
        ),
    ]
