# Generated by Django 4.2.4 on 2026-05-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realty',
            name='commercial_type',
            field=models.CharField(blank=True, choices=[('office', 'Офис'), ('retail', 'Торговое помещение'), ('warehouse', 'Склад'), ('free_use', 'Помещение свободного назначения'), ('industrial', 'Производственное помещение')], max_length=20, null=True, verbose_name='Тип коммерческой недвижимости'),
        ),
    ]
