# Generated by Django 4.2.4 on 2025-11-13 16:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayInSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Кол-во показов')),
                ('realty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display_in_search', to='realty.realty', verbose_name='Недвижимость')),
            ],
            options={
                'verbose_name': 'Показ в поиске',
                'verbose_name_plural': 'Показы в поиске',
            },
        ),
        migrations.CreateModel(
            name='DisplayFullInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата показа')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Кол-во показов')),
                ('realty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display_full_info', to='realty.realty', verbose_name='Недвижимость')),
            ],
            options={
                'verbose_name': 'Показ полной инфо',
                'verbose_name_plural': 'Показы полной инфо',
            },
        ),
    ]
