# Generated by Django 4.2.4 on 2025-12-16 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0002_initial'),
        ('realty_displays', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displayinsearch',
            name='realty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display_in_search', to='realty.realty', unique=True, verbose_name='Недвижимость'),
        ),
        migrations.AlterUniqueTogether(
            name='displayfullinfo',
            unique_together={('realty', 'date')},
        ),
    ]
