# Generated by Django 4.2.4 on 2026-03-14 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realty', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('is_viewed', models.BooleanField(default=False, verbose_name='Просмотрено')),
                ('realty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='realty.realty', verbose_name='Объявление')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранное',
                'ordering': ['-added_at'],
                'indexes': [models.Index(fields=['user', 'is_viewed'], name='favorites_f_user_id_a1713e_idx'), models.Index(fields=['realty'], name='favorites_f_realty__241f28_idx')],
                'unique_together': {('user', 'realty')},
            },
        ),
    ]
