# Generated by Django 4.2.4 on 2025-11-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BathroomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Тип санузла')),
            ],
            options={
                'verbose_name': 'Тип санузла',
                'verbose_name_plural': 'Типы санузлов',
            },
        ),
        migrations.CreateModel(
            name='BuildingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Тип дома')),
            ],
            options={
                'verbose_name': 'Тип дома',
                'verbose_name_plural': 'Типы домов',
            },
        ),
        migrations.CreateModel(
            name='CommunicationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=50, verbose_name='Способ связи')),
            ],
            options={
                'verbose_name': 'Способ связи',
                'verbose_name_plural': 'Способы связи',
            },
        ),
        migrations.CreateModel(
            name='HousingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='Вторичное жилье', max_length=50, verbose_name='Тип жилья')),
            ],
            options={
                'verbose_name': 'Тип жилья',
                'verbose_name_plural': 'Типы жилья',
            },
        ),
        migrations.CreateModel(
            name='RealtyAdvStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, verbose_name='Статус объявления')),
            ],
            options={
                'verbose_name': 'Статус объявления',
                'verbose_name_plural': 'Статусы объявлений',
            },
        ),
        migrations.CreateModel(
            name='RealtyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Тип недвижимости')),
            ],
            options={
                'verbose_name': 'Тип недвижимости',
                'verbose_name_plural': 'Типы недвижимости',
            },
        ),
        migrations.CreateModel(
            name='RepairType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Тип ремонта')),
            ],
            options={
                'verbose_name': 'Тип ремонта',
                'verbose_name_plural': 'Типы ремонта',
            },
        ),
        migrations.CreateModel(
            name='RoomsNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_rooms', models.CharField(max_length=20, verbose_name='Количество комнат')),
            ],
            options={
                'verbose_name': 'Количество комнат',
                'verbose_name_plural': 'Количество комнат',
            },
        ),
        migrations.CreateModel(
            name='SaleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='Свободная продажа', max_length=50, verbose_name='Тип продажи')),
            ],
            options={
                'verbose_name': 'Тип продажи',
                'verbose_name_plural': 'Типы продажи',
            },
        ),
        migrations.CreateModel(
            name='TradeParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant', models.CharField(max_length=50, verbose_name='Участник сделки')),
            ],
            options={
                'verbose_name': 'Участник сделки',
                'verbose_name_plural': 'Участники сделок',
            },
        ),
    ]
