# Generated by Django 4.2.4 on 2026-05-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty_values', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtytype',
            name='is_commercial',
            field=models.BooleanField(default=False, verbose_name='Коммерческая недвижимость'),
        ),
    ]
