# Generated by Django 4.2.4 on 2025-11-13 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealtyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='realty_photos', verbose_name='Фото')),
                ('sorter', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('realty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realty_photos', to='realty.realty', verbose_name='Недвижимость')),
            ],
            options={
                'verbose_name': 'Фото недвижимости',
                'verbose_name_plural': 'Фото недвижимости',
                'ordering': ['sorter'],
            },
        ),
    ]
