# Generated by Django 4.2.4 on 2025-11-13 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blocking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Блокировка',
                'verbose_name_plural': 'Блокировки',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chat_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Message ID')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата + Время создания')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата + Время прочтения')),
                ('is_new', models.BooleanField(default=True, verbose_name='Не прочитано')),
                ('is_deleted_from', models.BooleanField(default=False, verbose_name='Удалено отправителем')),
                ('is_deleted_to', models.BooleanField(default=False, verbose_name='Удалено получателем')),
                ('sender_is_owner', models.BooleanField(verbose_name='отправлено владельцем')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chats.chat', verbose_name='Чат')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
