# Generated by Django 4.2.4 on 2025-11-13 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0001_initial'),
        ('realty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='user_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages_sent', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель'),
        ),
        migrations.AddField(
            model_name='message',
            name='user_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages_received', to=settings.AUTH_USER_MODEL, verbose_name='Получатель'),
        ),
        migrations.AddField(
            model_name='chat',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_chats', to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='chat',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owner_chats', to=settings.AUTH_USER_MODEL, verbose_name='Владелец недвижимости'),
        ),
        migrations.AddField(
            model_name='chat',
            name='realty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='realty.realty', verbose_name='Объект недвижимости'),
        ),
        migrations.AddField(
            model_name='blocking',
            name='user_who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='who_blocked', to=settings.AUTH_USER_MODEL, verbose_name='Кто заблокировал'),
        ),
        migrations.AddField(
            model_name='blocking',
            name='user_whom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='whom_blocked', to=settings.AUTH_USER_MODEL, verbose_name='Кого заблокировали'),
        ),
        migrations.AddConstraint(
            model_name='chat',
            constraint=models.UniqueConstraint(fields=('realty', 'owner', 'client'), name='unique_chat_participants'),
        ),
    ]
