# Generated by Django 4.2.4 on 2026-08-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_alter_message_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(max_length=2500, verbose_name='Сообщение'),
        ),
    ]
