# Generated by Django 4.2.4 on 2026-09-22 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0003_realty_commercial_type'),
        ('chats', '0004_alter_message_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='realty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chats', to='realty.realty', verbose_name='Объект недвижимости'),
        ),
    ]
