# Generated by Django 4.2.4 on 2026-09-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_alter_chat_realty'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_deleted_client',
            field=models.BooleanField(default=False, verbose_name='Удален клиентом'),
        ),
        migrations.AddField(
            model_name='chat',
            name='is_deleted_owner',
            field=models.BooleanField(default=False, verbose_name='Удален владельцем'),
        ),
    ]
