# Generated by Django 4.2.4 on 2025-11-13 16:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realty_values', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fridge', models.BooleanField(default=False, verbose_name='Холодильник')),
                ('internet', models.BooleanField(default=False, verbose_name='Интернет')),
                ('conditioner', models.BooleanField(default=False, verbose_name='Кондиционер')),
                ('tv', models.BooleanField(default=False, verbose_name='Телевизор')),
                ('dishwasher', models.BooleanField(default=False, verbose_name='Посудомоечная машина')),
                ('washing_machine', models.BooleanField(default=False, verbose_name='Стиральная машина')),
                ('garbage_chute', models.BooleanField(default=False, verbose_name='Мусоропровод')),
                ('kids_allowed', models.BooleanField(default=False, verbose_name='Можно с детьми')),
                ('animals_allowed', models.BooleanField(default=False, verbose_name='Можно с животными')),
            ],
            options={
                'verbose_name': 'Особенности аренды',
                'verbose_name_plural': 'Особенности аренды',
                'ordering': ['internet'],
            },
        ),
        migrations.CreateModel(
            name='SalesParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('housing_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_parameters', to='realty_values.housingtype', verbose_name='Тип жилья')),
                ('sale_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_parameters', to='realty_values.saletype', verbose_name='Тип продажи')),
            ],
            options={
                'verbose_name': 'Параметры продажи',
                'verbose_name_plural': 'Параметры продаж',
                'ordering': ['housing_type'],
            },
        ),
        migrations.CreateModel(
            name='LeasePayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit', models.PositiveIntegerField(blank=True, null=True, verbose_name='Залог')),
                ('communal_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lease_payments_counters', to='realty_values.tradeparticipant', verbose_name='Оплата ЖКХ')),
                ('counters_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lease_payments_communal', to='realty_values.tradeparticipant', verbose_name='Оплата счетчиков')),
            ],
            options={
                'verbose_name': 'Платежи аренды',
                'verbose_name_plural': 'Платежи аренды',
                'ordering': ['deposit'],
            },
        ),
        migrations.CreateModel(
            name='CommonCharacteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('furniture', models.BooleanField(default=False, verbose_name='Мебель')),
                ('courtyard_view', models.BooleanField(default=False, verbose_name='Вид во двор')),
                ('street_view', models.BooleanField(default=False, verbose_name='Вид на улицу')),
                ('bathroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='common_characteristics', to='realty_values.bathroomtype', verbose_name='Тип санузла')),
                ('repair_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='common_characteristics', to='realty_values.repairtype', verbose_name='Тип ремонта')),
            ],
            options={
                'verbose_name': 'Общие характеристики',
                'verbose_name_plural': 'Общие характеристики',
                'ordering': ['repair_type'],
            },
        ),
        migrations.CreateModel(
            name='AboutBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_built', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1500), django.core.validators.MaxValueValidator(2025)], verbose_name='Год постройки')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='about_houses', to='realty_values.buildingtype', verbose_name='Тип дома')),
            ],
            options={
                'verbose_name': 'О доме',
                'verbose_name_plural': 'О домах',
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='AboutApartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.FloatField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(1500)], verbose_name='Площадь квартиры кв.м.')),
                ('loggia', models.BooleanField(default=False, verbose_name='Лоджия')),
                ('balcony', models.BooleanField(default=False, verbose_name='Балкон')),
                ('elevator', models.BooleanField(default=False, verbose_name='Лифт')),
                ('floor', models.PositiveSmallIntegerField(default=False, verbose_name='Этаж')),
                ('floors_number', models.PositiveSmallIntegerField(default=False, verbose_name='Этажность')),
                ('number_of_rooms', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='about_apartments', to='realty_values.roomsnumber', verbose_name='Кол-во комнат')),
            ],
            options={
                'verbose_name': 'О квартире',
                'verbose_name_plural': 'О квартирах',
                'ordering': ['number_of_rooms'],
            },
        ),
    ]
