# Generated by Django 4.2.4 on 2026-02-05 19:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty_specificities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutbuilding',
            name='year_built',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1500), django.core.validators.MaxValueValidator(2026)], verbose_name='Год постройки'),
        ),
    ]
