# Generated by Django 4.2.4 on 2025-11-13 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0001_initial'),
        ('realty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='realty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='realty.realty', verbose_name='Недвижимость'),
        ),
        migrations.AddField(
            model_name='notification',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='notifications.notificationtemplate', verbose_name='Шаблон'),
        ),
    ]
