name: Dev purchase_of_housing workflow

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
    types: [closed]

jobs:
  build_and_push_to_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker 
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v4 
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/purchase_of_housing_backend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push_to_docker_hub
    # if: github.ref == 'refs/heads/master'   запуск deploy только в том случае, если workflow запускается от ветки master.
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Copy nginx.conf via ssh
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSPHRASE }}
          source: "nginx.conf"
          target: "purchase_of_housing_backend"
      - name: Copy docker-compose.yml via ssh
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          # key: ${{ secrets.SSH_KEY }}
          password: ${{ secrets.PASSPHRASE }}
          source: "docker-compose.yml"
          target: "purchase_of_housing_backend"
      - name: executing remote ssh commands to deploy using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          # key: ${{ secrets.SSH_KEY }}
          password: ${{ secrets.PASSPHRASE }}
          script: |
            cd purchase_of_housing_backend
            # Удаляем старые контейнеры, но не удаляем тома данных
            sudo docker compose -f docker-compose.yml pull
            sudo docker compose -f docker-compose.yml down --volumes=false
            
            # ------- Обновление контейнеры без перезаписи томов
            sudo docker compose -f docker-compose.yml up -d --build
            
            # ------- Раньше удаляли все "ненужные файлы" 
            # ------- sudo docker system prune -af
            
            # ------- Теперь удаляем все, КРОМЕ тома БД - и это не сработало - ошибка -   
            # ------- Error response from daemon: invalid filter 'volume!'
            # ------- sudo docker system prune -af --volumes --filter "volume!=purchase_housing_pgdata"
            
            # Удаляем все тома, кроме тома БД
            sudo docker volume prune -f --filter "label!=keep"
            sudo docker volume create --label keep pgdata_alfa
            
            rm -f .env
            touch .env
            echo POSTGRES_DB=${{ secrets.POSTGRES_DB }} >> .env
            echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> .env
            echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
            echo DB_HOST=${{ secrets.DB_HOST }} >> .env
            echo DB_PORT=${{ secrets.DB_PORT }} >> .env
            echo SECRET_KEY="${{ secrets.SECRET_KEY }}" >> .env
            echo HOST_IP="${{ secrets.HOST_IP }}" >> .env
            echo DOMAIN="${{ secrets.DOMAIN }}" >> .env
            echo DEBUG=${{ secrets.DEBUG }} >> .env
            sudo docker compose up -d --build
            sudo docker compose exec -T backend bash -c "
            python manage.py makemigrations &&
            python manage.py migrate &&
            python manage.py collectstatic --no-input"
            
            
            sudo docker compose exec -T backend bash -c "
            echo "Проверка пустая ли база"
            # ---- КАЖЕТСЯ ЭТА ЧАСТЬ НЕ РАБОТАЕТ!!!
            # ---- Проверяем, есть ли данные в базе. Если данных нет, загружаем их из data.json
            if ! python manage.py dumpdata --exclude auth.permission --exclude contenttypes | grep -q .; then
              python manage.py loaddata data.json
            fi &&
            # ---- В любом случае переустанавливаем разрешения модераторов!
            python manage.py fix_moderator_permissions &&
            nohup python manage.py qcluster > /dev/null 2>&1 &"

          # интересный момент
          # -- ПРИ ПЕРВОМ запуске скрипта, старый том с базой данных будет удален - так как еще не имеет названия,
          #    но к концу скрипта именованный том уже будет заполнен тестовыми данными из DATA.JSON
          # -- ПРИ ВТОРОМ запуске скрипта том уже будет существовать, а вот тестовые данные уже загружать не надо!

          # Для обхода этой особенности заменим код на код с условиями, а старый пока сохраним тут:
          # python manage.py loaddata data.json &&
          # python manage.py fix_moderator_permissions &&
          # nohup python manage.py qcluster > /dev/null 2>&1 &"

