# Generated by Django 4.2.4 on 2025-11-13 16:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Округ')),
            ],
            options={
                'verbose_name': 'Округ',
                'verbose_name_plural': 'Округа',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MetroLine',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('line_id', models.CharField(help_text="Привычный код станции (например, '1', '8A', 'D1')", max_length=10, unique=True, verbose_name='Идентификатор линии')),
                ('name', models.CharField(max_length=150, verbose_name='Название линии')),
                ('name_full', models.CharField(max_length=150, verbose_name='Полное Название линии')),
                ('city', models.CharField(default='Москва', max_length=50, verbose_name='Город')),
                ('color', models.CharField(help_text="Шестнадцатеричный код цвета без '#'", max_length=6, verbose_name='Цвет линии (HEX)')),
            ],
            options={
                'verbose_name': 'Линия метро',
                'verbose_name_plural': 'Линии метро',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Район')),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Районы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Улица')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='streets', to='realty_addresses.city', verbose_name='Город')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='streets', to='realty_addresses.district', verbose_name='Округ')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='streets', to='realty_addresses.zone', verbose_name='Район')),
            ],
            options={
                'verbose_name': 'Улица',
                'verbose_name_plural': 'Улицы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Metro',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Название станции (краткое)')),
                ('name_full', models.CharField(default='', help_text="Например, 'Авиамоторная (D3)'", max_length=250, verbose_name='Полное название станции')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('is_closed', models.BooleanField(blank=True, null=True, verbose_name='Станция закрыта')),
                ('line', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='realty_addresses.metroline', verbose_name='Линия метро')),
            ],
            options={
                'verbose_name': 'Станция метро',
                'verbose_name_plural': 'Станции метро',
                'ordering': ['name', 'line__id'],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_number', models.CharField(max_length=50, verbose_name='Номер дома')),
                ('corpus', models.CharField(blank=True, max_length=50, null=True, verbose_name='Корпус')),
                ('building', models.CharField(blank=True, max_length=50, null=True, verbose_name='Строение')),
                ('ownership', models.CharField(blank=True, max_length=50, null=True, verbose_name='Владение')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('minutes_to_metro', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message='Минимальное время не может быть меньше 1 минуты!'), django.core.validators.MaxValueValidator(60, message='Минимальное время не может быть больше 60 минут!')], verbose_name='Минут до метро')),
                ('metro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='realty_addresses.metro', verbose_name='Метро')),
                ('street', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='realty_addresses.street', verbose_name='Улица')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
                'ordering': ['street'],
            },
        ),
    ]
